reset_db: add --use-existing-backup option to skip making a backup and just use the existing backup

diff --git a/reset_db b/reset_db
--- a/reset_db
+++ b/reset_db
@@ -7,26 +7,32 @@ db_user=machine_manager
 db_name=machine_manager
 backup_file=~/.config/machine_manager/backup.sql
 
-# Make the backup folder if it doesn't already exist
-mkdir -p "$(dirname "$backup_file")"
-# Rotate existing backups
-mv "$backup_file.2" "$backup_file.3" 2> /dev/null || true
-mv "$backup_file.1" "$backup_file.2" 2> /dev/null || true
-mv "$backup_file"   "$backup_file.1" 2> /dev/null || true
+make_backup() {
+	# Make the backup folder if it doesn't already exist
+	mkdir -p "$(dirname "$backup_file")"
+	# Rotate existing backups
+	mv "$backup_file.2" "$backup_file.3" 2> /dev/null || true
+	mv "$backup_file.1" "$backup_file.2" 2> /dev/null || true
+	mv "$backup_file"   "$backup_file.1" 2> /dev/null || true
 
-# For the backup, create a table with a subset of the machines table, containing
-# just the columns with data that can't be probed.  This way, after a big schema
-# change, we still typically will not need to edit backup.sql for the restore.
-create_backup_subset="\
-DROP TABLE IF EXISTS machines_backup_subset;
-CREATE TABLE         machines_backup_subset AS SELECT hostname, ip, ssh_port, tags, added_time FROM machines;
-"
-echo "$create_backup_subset"  | ssh "$ssh_user_host" "psql -v ON_ERROR_STOP=1 -d $db_name"
+	# For the backup, create a table with a subset of the machines table, containing
+	# just the columns with data that can't be probed.  This way, after a big schema
+	# change, we still typically will not need to edit backup.sql for the restore.
+	create_backup_subset="\
+	DROP TABLE IF EXISTS machines_backup_subset;
+	CREATE TABLE         machines_backup_subset AS SELECT hostname, ip, ssh_port, tags, added_time FROM machines;
+	"
+	echo "$create_backup_subset"  | ssh "$ssh_user_host" "psql -v ON_ERROR_STOP=1 -d $db_name"
 
-# Create the backup file
-ssh "$ssh_user_host" "pg_dump --data-only --table machines_backup_subset machine_manager" > "$backup_file"
-# Fix the backup to restore into the machines table
-sed -i -r 's,^COPY machines_backup_subset ,COPY machines ,' "$backup_file"
+	# Create the backup file
+	ssh "$ssh_user_host" "pg_dump --data-only --table machines_backup_subset machine_manager" > "$backup_file"
+	# Fix the backup to restore into the machines table
+	sed -i -r 's,^COPY machines_backup_subset ,COPY machines ,' "$backup_file"
+}
+
+if [[ "$1" != "--use-existing-backup" ]]; then
+	make_backup
+fi
 
 # Drop database, create database, import schema and backup
 reset_db="\
