Make reset_db back up and restore the data

diff --git a/reset_db b/reset_db
--- a/reset_db
+++ b/reset_db
@@ -1,9 +1,14 @@
 #!/bin/bash
 
+set -eu -o pipefail
+
+ssh_user_host=postgres@localhost
 db_user=machine_manager
 db_name=machine_manager
+backup_file=~/.config/machine_manager/backup.sql
 
-set -eu -o pipefail
+mkdir -p "$(dirname "$backup_file")"
+ssh "$ssh_user_host" "pg_dump --data-only machine_manager" > "$backup_file"
 
 reset_db="\
 DROP DATABASE IF EXISTS          $db_name;
@@ -12,5 +17,5 @@ GRANT ALL PRIVILEGES ON DATABASE $db_name TO $db_user;
 ALTER DATABASE                   $db_name SET bytea_output TO 'escape';
 "
 
-echo "$reset_db" | ssh postgres@localhost "psql -v ON_ERROR_STOP=1"
-ssh postgres@localhost "psql -v ON_ERROR_STOP=1 -d $db_name" < schema.sql
+echo "$reset_db"              | ssh "$ssh_user_host" "psql -v ON_ERROR_STOP=1"
+cat schema.sql "$backup_file" | ssh "$ssh_user_host" "psql -v ON_ERROR_STOP=1 -d $db_name"
